-- ============================================================
-- AIRPORTS MASTER — run once in Supabase SQL Editor
-- Covers all Indian airports + major international airports
-- ============================================================

CREATE TABLE IF NOT EXISTS airports (
  iata_code   TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  city        TEXT NOT NULL,
  country     TEXT NOT NULL,
  country_code TEXT NOT NULL DEFAULT 'IN'
);

INSERT INTO airports (iata_code, name, city, country, country_code) VALUES

-- ── INDIA ────────────────────────────────────────────────────
('DEL','Indira Gandhi International Airport','Delhi','India','IN'),
('BOM','Chhatrapati Shivaji Maharaj International Airport','Mumbai','India','IN'),
('BLR','Kempegowda International Airport','Bengaluru','India','IN'),
('HYD','Rajiv Gandhi International Airport','Hyderabad','India','IN'),
('MAA','Chennai International Airport','Chennai','India','IN'),
('CCU','Netaji Subhas Chandra Bose International Airport','Kolkata','India','IN'),
('AMD','Sardar Vallabhbhai Patel International Airport','Ahmedabad','India','IN'),
('PNQ','Pune Airport','Pune','India','IN'),
('GOI','Goa International Airport (Dabolim)','Goa','India','IN'),
('COK','Cochin International Airport','Kochi','India','IN'),
('JAI','Jaipur International Airport','Jaipur','India','IN'),
('ATQ','Sri Guru Ram Dass Jee International Airport','Amritsar','India','IN'),
('IXC','Chandigarh International Airport','Chandigarh','India','IN'),
('LKO','Chaudhary Charan Singh International Airport','Lucknow','India','IN'),
('VNS','Lal Bahadur Shastri International Airport','Varanasi','India','IN'),
('PAT','Jay Prakash Narayan Airport','Patna','India','IN'),
('BBI','Biju Patnaik International Airport','Bhubaneswar','India','IN'),
('IXR','Birsa Munda Airport','Ranchi','India','IN'),
('NAG','Dr. Babasaheb Ambedkar International Airport','Nagpur','India','IN'),
('GAU','Lokpriya Gopinath Bordoloi International Airport','Guwahati','India','IN'),
('IXZ','Veer Savarkar International Airport','Port Blair','India','IN'),
('TRV','Trivandrum International Airport','Thiruvananthapuram','India','IN'),
('CJB','Coimbatore International Airport','Coimbatore','India','IN'),
('IXM','Madurai Airport','Madurai','India','IN'),
('TRZ','Tiruchirappalli International Airport','Tiruchirappalli','India','IN'),
('SXR','Sheikh ul-Alam International Airport','Srinagar','India','IN'),
('IXB','Bagdogra Airport','Siliguri','India','IN'),
('VTZ','Visakhapatnam Airport','Visakhapatnam','India','IN'),
('VGA','Vijayawada Airport','Vijayawada','India','IN'),
('TIR','Tirupati Airport','Tirupati','India','IN'),
('IXE','Mangaluru International Airport','Mangaluru','India','IN'),
('IXL','Kushok Bakula Rimpochee Airport','Leh','India','IN'),
('DED','Jolly Grant Airport','Dehradun','India','IN'),
('DHM','Gaggal Airport','Dharamshala','India','IN'),
('KUU','Kullu Manali Airport','Kullu','India','IN'),
('GWL','Gwalior Airport','Gwalior','India','IN'),
('JDH','Jodhpur Airport','Jodhpur','India','IN'),
('UDR','Maharana Pratap Airport','Udaipur','India','IN'),
('BHO','Raja Bhoj International Airport','Bhopal','India','IN'),
('IDR','Devi Ahilya Bai Holkar Airport','Indore','India','IN'),
('RPR','Swami Vivekananda Airport','Raipur','India','IN'),
('IMF','Imphal Airport','Imphal','India','IN'),
('IXJ','Jammu Airport','Jammu','India','IN'),
('IXS','Silchar Airport','Silchar','India','IN'),
('IXA','Maharaja Bir Bikram Airport','Agartala','India','IN'),
('DIB','Dibrugarh Airport','Dibrugarh','India','IN'),
('BDQ','Vadodara Airport','Vadodara','India','IN'),
('STV','Surat Airport','Surat','India','IN'),
('HJR','Khajuraho Airport','Khajuraho','India','IN'),
('JLR','Jabalpur Airport','Jabalpur','India','IN'),
('AGR','Agra Airport','Agra','India','IN'),
('HBX','Hubballi Airport','Hubballi','India','IN'),
('MYQ','Mysore Airport','Mysore','India','IN'),
('IXU','Aurangabad Airport','Aurangabad','India','IN'),
('JGA','Jamnagar Airport','Jamnagar','India','IN'),
('RAJ','Rajkot Airport','Rajkot','India','IN'),
('IXY','Kandla Airport','Kandla','India','IN'),
('BHJ','Bhuj Airport','Bhuj','India','IN'),
('PBD','Porbandar Airport','Porbandar','India','IN'),
('CDP','Cuddapah Airport','Kadapa','India','IN'),
('RJA','Rajahmundry Airport','Rajahmundry','India','IN'),
('HGS','Hirasar Airport','Rajkot','India','IN'),
('GOP','Gorakhpur Airport','Gorakhpur','India','IN'),
('KNU','Kanpur Airport','Kanpur','India','IN'),
('AYJ','Allahabad Airport','Prayagraj','India','IN'),
('TEZ','Tezpur Airport','Tezpur','India','IN'),
('JRH','Jorhat Airport','Jorhat','India','IN'),
('SSA','Silchar Airport','Silchar','India','IN'),
('LDA','Malda Airport','Malda','India','IN'),
('RRK','Rourkela Airport','Rourkela','India','IN'),

-- ── MIDDLE EAST ─────────────────────────────────────────────
('DXB','Dubai International Airport','Dubai','United Arab Emirates','AE'),
('AUH','Abu Dhabi International Airport','Abu Dhabi','United Arab Emirates','AE'),
('SHJ','Sharjah International Airport','Sharjah','United Arab Emirates','AE'),
('DOH','Hamad International Airport','Doha','Qatar','QA'),
('BAH','Bahrain International Airport','Manama','Bahrain','BH'),
('MCT','Muscat International Airport','Muscat','Oman','OM'),
('KWI','Kuwait International Airport','Kuwait City','Kuwait','KW'),
('RUH','King Khalid International Airport','Riyadh','Saudi Arabia','SA'),
('JED','King Abdulaziz International Airport','Jeddah','Saudi Arabia','SA'),
('MED','Prince Mohammad Bin Abdulaziz Airport','Medina','Saudi Arabia','SA'),
('AMM','Queen Alia International Airport','Amman','Jordan','JO'),
('BEY','Rafic Hariri International Airport','Beirut','Lebanon','LB'),
('TLV','Ben Gurion International Airport','Tel Aviv','Israel','IL'),

-- ── SOUTH ASIA ─────────────────────────────────────────────
('KTM','Tribhuvan International Airport','Kathmandu','Nepal','NP'),
('PBH','Paro International Airport','Paro','Bhutan','BT'),
('DAC','Hazrat Shahjalal International Airport','Dhaka','Bangladesh','BD'),
('CMB','Bandaranaike International Airport','Colombo','Sri Lanka','LK'),
('MLE','Velana International Airport','Malé','Maldives','MV'),
('ISB','Islamabad International Airport','Islamabad','Pakistan','PK'),
('KHI','Jinnah International Airport','Karachi','Pakistan','PK'),
('LHE','Allama Iqbal International Airport','Lahore','Pakistan','PK'),

-- ── SOUTHEAST ASIA ─────────────────────────────────────────
('SIN','Singapore Changi Airport','Singapore','Singapore','SG'),
('BKK','Suvarnabhumi International Airport','Bangkok','Thailand','TH'),
('DMK','Don Mueang International Airport','Bangkok','Thailand','TH'),
('HKT','Phuket International Airport','Phuket','Thailand','TH'),
('CNX','Chiang Mai International Airport','Chiang Mai','Thailand','TH'),
('USM','Samui Airport','Koh Samui','Thailand','TH'),
('KUL','Kuala Lumpur International Airport','Kuala Lumpur','Malaysia','MY'),
('PEN','Penang International Airport','Penang','Malaysia','MY'),
('BKI','Kota Kinabalu International Airport','Kota Kinabalu','Malaysia','MY'),
('LGK','Langkawi International Airport','Langkawi','Malaysia','MY'),
('CGK','Soekarno-Hatta International Airport','Jakarta','Indonesia','ID'),
('DPS','Ngurah Rai International Airport','Bali','Indonesia','ID'),
('MNL','Ninoy Aquino International Airport','Manila','Philippines','PH'),
('CEB','Mactan-Cebu International Airport','Cebu','Philippines','PH'),
('SGN','Tan Son Nhat International Airport','Ho Chi Minh City','Vietnam','VN'),
('HAN','Noi Bai International Airport','Hanoi','Vietnam','VN'),
('DAD','Da Nang International Airport','Da Nang','Vietnam','VN'),
('REP','Siem Reap-Angkor International Airport','Siem Reap','Cambodia','KH'),
('PNH','Phnom Penh International Airport','Phnom Penh','Cambodia','KH'),
('RGN','Yangon International Airport','Yangon','Myanmar','MM'),
('VTE','Wattay International Airport','Vientiane','Laos','LA'),

-- ── EAST ASIA ──────────────────────────────────────────────
('HKG','Hong Kong International Airport','Hong Kong','Hong Kong','HK'),
('PVG','Shanghai Pudong International Airport','Shanghai','China','CN'),
('PEK','Beijing Capital International Airport','Beijing','China','CN'),
('PKX','Beijing Daxing International Airport','Beijing','China','CN'),
('CAN','Guangzhou Baiyun International Airport','Guangzhou','China','CN'),
('CTU','Chengdu Tianfu International Airport','Chengdu','China','CN'),
('ICN','Incheon International Airport','Seoul','South Korea','KR'),
('GMP','Gimpo International Airport','Seoul','South Korea','KR'),
('NRT','Narita International Airport','Tokyo','Japan','JP'),
('HND','Tokyo Haneda Airport','Tokyo','Japan','JP'),
('KIX','Kansai International Airport','Osaka','Japan','JP'),
('TPE','Taiwan Taoyuan International Airport','Taipei','Taiwan','TW'),
('MFM','Macau International Airport','Macau','Macau','MO'),

-- ── EUROPE ─────────────────────────────────────────────────
('LHR','London Heathrow Airport','London','United Kingdom','GB'),
('LGW','London Gatwick Airport','London','United Kingdom','GB'),
('STN','London Stansted Airport','London','United Kingdom','GB'),
('MAN','Manchester Airport','Manchester','United Kingdom','GB'),
('EDI','Edinburgh Airport','Edinburgh','United Kingdom','GB'),
('CDG','Charles de Gaulle Airport','Paris','France','FR'),
('ORY','Paris Orly Airport','Paris','France','FR'),
('NCE','Nice Côte d''Azur Airport','Nice','France','FR'),
('FCO','Leonardo da Vinci International Airport','Rome','Italy','IT'),
('MXP','Milan Malpensa Airport','Milan','Italy','IT'),
('VCE','Venice Marco Polo Airport','Venice','Italy','IT'),
('AMS','Amsterdam Airport Schiphol','Amsterdam','Netherlands','NL'),
('FRA','Frankfurt Airport','Frankfurt','Germany','DE'),
('MUC','Munich Airport','Munich','Germany','DE'),
('BER','Berlin Brandenburg Airport','Berlin','Germany','DE'),
('BCN','Barcelona El Prat Airport','Barcelona','Spain','ES'),
('MAD','Adolfo Suárez Madrid-Barajas Airport','Madrid','Spain','ES'),
('ZRH','Zurich Airport','Zurich','Switzerland','CH'),
('GVA','Geneva Airport','Geneva','Switzerland','CH'),
('VIE','Vienna International Airport','Vienna','Austria','AT'),
('PRG','Václav Havel Airport Prague','Prague','Czech Republic','CZ'),
('BUD','Budapest Ferenc Liszt International Airport','Budapest','Hungary','HU'),
('WAW','Warsaw Chopin Airport','Warsaw','Poland','PL'),
('ATH','Athens International Airport','Athens','Greece','GR'),
('SKG','Thessaloniki Airport','Thessaloniki','Greece','GR'),
('IST','Istanbul Airport','Istanbul','Turkey','TR'),
('SAW','Sabiha Gökçen International Airport','Istanbul','Turkey','TR'),
('AYT','Antalya Airport','Antalya','Turkey','TR'),
('DUB','Dublin Airport','Dublin','Ireland','IE'),
('CPH','Copenhagen Airport','Copenhagen','Denmark','DK'),
('ARN','Stockholm Arlanda Airport','Stockholm','Sweden','SE'),
('OSL','Oslo Gardermoen Airport','Oslo','Norway','NO'),
('HEL','Helsinki-Vantaa Airport','Helsinki','Finland','FI'),
('LIS','Lisbon Humberto Delgado Airport','Lisbon','Portugal','PT'),
('OPO','Francisco de Sá Carneiro Airport','Porto','Portugal','PT'),
('BRU','Brussels Airport','Brussels','Belgium','BE'),
('RKV','Reykjavik Airport','Reykjavik','Iceland','IS'),
('KEF','Keflavík International Airport','Reykjavik','Iceland','IS'),

-- ── AMERICAS ────────────────────────────────────────────────
('JFK','John F. Kennedy International Airport','New York','United States','US'),
('LGA','LaGuardia Airport','New York','United States','US'),
('EWR','Newark Liberty International Airport','Newark','United States','US'),
('LAX','Los Angeles International Airport','Los Angeles','United States','US'),
('ORD','O''Hare International Airport','Chicago','United States','US'),
('MDW','Chicago Midway International Airport','Chicago','United States','US'),
('DFW','Dallas/Fort Worth International Airport','Dallas','United States','US'),
('ATL','Hartsfield-Jackson Atlanta International Airport','Atlanta','United States','US'),
('MIA','Miami International Airport','Miami','United States','US'),
('SFO','San Francisco International Airport','San Francisco','United States','US'),
('SEA','Seattle-Tacoma International Airport','Seattle','United States','US'),
('BOS','Logan International Airport','Boston','United States','US'),
('IAD','Washington Dulles International Airport','Washington DC','United States','US'),
('DCA','Ronald Reagan Washington National Airport','Washington DC','United States','US'),
('LAS','Harry Reid International Airport','Las Vegas','United States','US'),
('MCO','Orlando International Airport','Orlando','United States','US'),
('HNL','Daniel K. Inouye International Airport','Honolulu','United States','US'),
('YYZ','Toronto Pearson International Airport','Toronto','Canada','CA'),
('YVR','Vancouver International Airport','Vancouver','Canada','CA'),
('YUL','Montréal-Pierre Elliott Trudeau International Airport','Montreal','Canada','CA'),
('GRU','São Paulo-Guarulhos International Airport','São Paulo','Brazil','BR'),
('GIG','Rio de Janeiro-Galeão International Airport','Rio de Janeiro','Brazil','BR'),
('MEX','Benito Juárez International Airport','Mexico City','Mexico','MX'),
('CUN','Cancún International Airport','Cancún','Mexico','MX'),
('BOG','El Dorado International Airport','Bogotá','Colombia','CO'),
('LIM','Jorge Chávez International Airport','Lima','Peru','PE'),
('EZE','Ministro Pistarini International Airport','Buenos Aires','Argentina','AR'),

-- ── OCEANIA ─────────────────────────────────────────────────
('SYD','Sydney Kingsford Smith Airport','Sydney','Australia','AU'),
('MEL','Melbourne Airport','Melbourne','Australia','AU'),
('BNE','Brisbane Airport','Brisbane','Australia','AU'),
('PER','Perth Airport','Perth','Australia','AU'),
('ADL','Adelaide Airport','Adelaide','Australia','AU'),
('AKL','Auckland Airport','Auckland','New Zealand','NZ'),
('CHC','Christchurch Airport','Christchurch','New Zealand','NZ'),

-- ── AFRICA ──────────────────────────────────────────────────
('JNB','O.R. Tambo International Airport','Johannesburg','South Africa','ZA'),
('CPT','Cape Town International Airport','Cape Town','South Africa','ZA'),
('DUR','King Shaka International Airport','Durban','South Africa','ZA'),
('NBO','Jomo Kenyatta International Airport','Nairobi','Kenya','KE'),
('ADD','Bole International Airport','Addis Ababa','Ethiopia','ET'),
('CAI','Cairo International Airport','Cairo','Egypt','EG'),
('HRG','Hurghada International Airport','Hurghada','Egypt','EG'),
('SSH','Sharm el-Sheikh International Airport','Sharm el-Sheikh','Egypt','EG'),
('CMN','Mohammed V International Airport','Casablanca','Morocco','MA'),
('RAK','Marrakesh Menara Airport','Marrakesh','Morocco','MA'),
('TUN','Tunis-Carthage International Airport','Tunis','Tunisia','TN'),
('LOS','Murtala Muhammed International Airport','Lagos','Nigeria','NG'),
('ACC','Kotoka International Airport','Accra','Ghana','GH'),
('DAR','Julius Nyerere International Airport','Dar es Salaam','Tanzania','TZ'),
('MRU','Sir Seewoosagur Ramgoolam International Airport','Mauritius','Mauritius','MU'),
('SEZ','Seychelles International Airport','Mahé','Seychelles','SC')

ON CONFLICT (iata_code) DO UPDATE SET
  name         = EXCLUDED.name,
  city         = EXCLUDED.city,
  country      = EXCLUDED.country,
  country_code = EXCLUDED.country_code;

-- Full-text search index for fast autocomplete
CREATE INDEX IF NOT EXISTS idx_airports_city ON airports USING gin(to_tsvector('simple', city));
CREATE INDEX IF NOT EXISTS idx_airports_name ON airports USING gin(to_tsvector('simple', name));
CREATE INDEX IF NOT EXISTS idx_airports_iata ON airports (iata_code);
