-- ============================================================
-- TRAVEL CITIES MASTER — run once in Supabase SQL Editor
-- Used for hotel search autocomplete (TripJack city IDs get
-- cached here automatically on first lookup per city)
-- ============================================================

CREATE TABLE IF NOT EXISTS travel_cities (
  id           SERIAL PRIMARY KEY,
  name         TEXT NOT NULL,
  state        TEXT,
  country      TEXT NOT NULL DEFAULT 'India',
  country_code TEXT NOT NULL DEFAULT 'IN',
  tj_city_id   TEXT,
  UNIQUE (name, country_code)
);

INSERT INTO travel_cities (name, state, country, country_code) VALUES

-- ── INDIA — Metro & Major ───────────────────────────────────
('Delhi','Delhi','India','IN'),
('New Delhi','Delhi','India','IN'),
('Mumbai','Maharashtra','India','IN'),
('Bengaluru','Karnataka','India','IN'),
('Bangalore','Karnataka','India','IN'),
('Hyderabad','Telangana','India','IN'),
('Chennai','Tamil Nadu','India','IN'),
('Kolkata','West Bengal','India','IN'),
('Ahmedabad','Gujarat','India','IN'),
('Pune','Maharashtra','India','IN'),
('Surat','Gujarat','India','IN'),
('Jaipur','Rajasthan','India','IN'),
('Lucknow','Uttar Pradesh','India','IN'),
('Kanpur','Uttar Pradesh','India','IN'),
('Nagpur','Maharashtra','India','IN'),
('Indore','Madhya Pradesh','India','IN'),
('Bhopal','Madhya Pradesh','India','IN'),
('Visakhapatnam','Andhra Pradesh','India','IN'),
('Patna','Bihar','India','IN'),
('Vadodara','Gujarat','India','IN'),
('Rajkot','Gujarat','India','IN'),

-- ── INDIA — Tourism ─────────────────────────────────────────
('Goa','Goa','India','IN'),
('Panaji','Goa','India','IN'),
('Agra','Uttar Pradesh','India','IN'),
('Varanasi','Uttar Pradesh','India','IN'),
('Prayagraj','Uttar Pradesh','India','IN'),
('Allahabad','Uttar Pradesh','India','IN'),
('Mathura','Uttar Pradesh','India','IN'),
('Vrindavan','Uttar Pradesh','India','IN'),
('Amritsar','Punjab','India','IN'),
('Chandigarh','Punjab','India','IN'),
('Shimla','Himachal Pradesh','India','IN'),
('Manali','Himachal Pradesh','India','IN'),
('Dharamshala','Himachal Pradesh','India','IN'),
('McLeod Ganj','Himachal Pradesh','India','IN'),
('Kasol','Himachal Pradesh','India','IN'),
('Mussoorie','Uttarakhand','India','IN'),
('Nainital','Uttarakhand','India','IN'),
('Rishikesh','Uttarakhand','India','IN'),
('Haridwar','Uttarakhand','India','IN'),
('Dehradun','Uttarakhand','India','IN'),
('Jim Corbett','Uttarakhand','India','IN'),
('Jodhpur','Rajasthan','India','IN'),
('Udaipur','Rajasthan','India','IN'),
('Pushkar','Rajasthan','India','IN'),
('Jaisalmer','Rajasthan','India','IN'),
('Bikaner','Rajasthan','India','IN'),
('Ajmer','Rajasthan','India','IN'),
('Mount Abu','Rajasthan','India','IN'),
('Coimbatore','Tamil Nadu','India','IN'),
('Madurai','Tamil Nadu','India','IN'),
('Ooty','Tamil Nadu','India','IN'),
('Kodaikanal','Tamil Nadu','India','IN'),
('Tirupati','Andhra Pradesh','India','IN'),
('Vijayawada','Andhra Pradesh','India','IN'),
('Kochi','Kerala','India','IN'),
('Thiruvananthapuram','Kerala','India','IN'),
('Munnar','Kerala','India','IN'),
('Alleppey','Kerala','India','IN'),
('Kumarakom','Kerala','India','IN'),
('Wayanad','Kerala','India','IN'),
('Thekkady','Kerala','India','IN'),
('Varkala','Kerala','India','IN'),
('Mysuru','Karnataka','India','IN'),
('Mysore','Karnataka','India','IN'),
('Hampi','Karnataka','India','IN'),
('Coorg','Karnataka','India','IN'),
('Chikmagalur','Karnataka','India','IN'),
('Gokarna','Karnataka','India','IN'),
('Mangaluru','Karnataka','India','IN'),
('Bhubaneswar','Odisha','India','IN'),
('Puri','Odisha','India','IN'),
('Konark','Odisha','India','IN'),
('Raipur','Chhattisgarh','India','IN'),
('Ranchi','Jharkhand','India','IN'),
('Guwahati','Assam','India','IN'),
('Kaziranga','Assam','India','IN'),
('Darjeeling','West Bengal','India','IN'),
('Siliguri','West Bengal','India','IN'),
('Gangtok','Sikkim','India','IN'),
('Leh','Ladakh','India','IN'),
('Srinagar','Jammu & Kashmir','India','IN'),
('Jammu','Jammu & Kashmir','India','IN'),
('Pahalgam','Jammu & Kashmir','India','IN'),
('Gulmarg','Jammu & Kashmir','India','IN'),
('Port Blair','Andaman & Nicobar','India','IN'),
('Havelock Island','Andaman & Nicobar','India','IN'),
('Ranthambore','Rajasthan','India','IN'),
('Khajuraho','Madhya Pradesh','India','IN'),

-- ── SOUTH ASIA ─────────────────────────────────────────────
('Kathmandu','',  'Nepal','NP'),
('Pokhara','',    'Nepal','NP'),
('Chitwan','',    'Nepal','NP'),
('Paro','',       'Bhutan','BT'),
('Thimphu','',    'Bhutan','BT'),
('Colombo','',    'Sri Lanka','LK'),
('Kandy','',      'Sri Lanka','LK'),
('Galle','',      'Sri Lanka','LK'),
('Dhaka','',      'Bangladesh','BD'),
('Malé','',       'Maldives','MV'),
('Baa Atoll','',  'Maldives','MV'),
('Ari Atoll','',  'Maldives','MV'),

-- ── MIDDLE EAST ─────────────────────────────────────────────
('Dubai','',       'United Arab Emirates','AE'),
('Abu Dhabi','',   'United Arab Emirates','AE'),
('Sharjah','',     'United Arab Emirates','AE'),
('Doha','',        'Qatar','QA'),
('Muscat','',      'Oman','OM'),
('Kuwait City','', 'Kuwait','KW'),
('Riyadh','',      'Saudi Arabia','SA'),
('Jeddah','',      'Saudi Arabia','SA'),
('Manama','',      'Bahrain','BH'),
('Amman','',       'Jordan','JO'),
('Petra','',       'Jordan','JO'),
('Beirut','',      'Lebanon','LB'),

-- ── SOUTHEAST ASIA ─────────────────────────────────────────
('Singapore','',      'Singapore','SG'),
('Bangkok','',        'Thailand','TH'),
('Phuket','',         'Thailand','TH'),
('Chiang Mai','',     'Thailand','TH'),
('Pattaya','',        'Thailand','TH'),
('Krabi','',          'Thailand','TH'),
('Koh Samui','',      'Thailand','TH'),
('Koh Phi Phi','',    'Thailand','TH'),
('Kuala Lumpur','',   'Malaysia','MY'),
('Penang','',         'Malaysia','MY'),
('Langkawi','',       'Malaysia','MY'),
('Kota Kinabalu','',  'Malaysia','MY'),
('Bali','',           'Indonesia','ID'),
('Jakarta','',        'Indonesia','ID'),
('Yogyakarta','',     'Indonesia','ID'),
('Manila','',         'Philippines','PH'),
('Cebu','',           'Philippines','PH'),
('Boracay','',        'Philippines','PH'),
('Ho Chi Minh City','','Vietnam','VN'),
('Hanoi','',          'Vietnam','VN'),
('Da Nang','',        'Vietnam','VN'),
('Hoi An','',         'Vietnam','VN'),
('Halong Bay','',     'Vietnam','VN'),
('Siem Reap','',      'Cambodia','KH'),
('Phnom Penh','',     'Cambodia','KH'),
('Yangon','',         'Myanmar','MM'),
('Bagan','',          'Myanmar','MM'),

-- ── EAST ASIA ──────────────────────────────────────────────
('Hong Kong','',   'Hong Kong','HK'),
('Macau','',       'Macau','MO'),
('Shanghai','',    'China','CN'),
('Beijing','',     'China','CN'),
('Guangzhou','',   'China','CN'),
('Chengdu','',     'China','CN'),
('Guilin','',      'China','CN'),
('Seoul','',       'South Korea','KR'),
('Busan','',       'South Korea','KR'),
('Tokyo','',       'Japan','JP'),
('Osaka','',       'Japan','JP'),
('Kyoto','',       'Japan','JP'),
('Taipei','',      'Taiwan','TW'),

-- ── EUROPE ─────────────────────────────────────────────────
('London','',      'United Kingdom','GB'),
('Edinburgh','',   'United Kingdom','GB'),
('Manchester','',  'United Kingdom','GB'),
('Paris','',       'France','FR'),
('Nice','',        'France','FR'),
('Lyon','',        'France','FR'),
('Rome','',        'Italy','IT'),
('Milan','',       'Italy','IT'),
('Venice','',      'Italy','IT'),
('Florence','',    'Italy','IT'),
('Amalfi','',      'Italy','IT'),
('Amsterdam','',   'Netherlands','NL'),
('Frankfurt','',   'Germany','DE'),
('Munich','',      'Germany','DE'),
('Berlin','',      'Germany','DE'),
('Barcelona','',   'Spain','ES'),
('Madrid','',      'Spain','ES'),
('Seville','',     'Spain','ES'),
('Ibiza','',       'Spain','ES'),
('Mallorca','',    'Spain','ES'),
('Zurich','',      'Switzerland','CH'),
('Geneva','',      'Switzerland','CH'),
('Interlaken','',  'Switzerland','CH'),
('Lucerne','',     'Switzerland','CH'),
('Vienna','',      'Austria','AT'),
('Salzburg','',    'Austria','AT'),
('Prague','',      'Czech Republic','CZ'),
('Budapest','',    'Hungary','HU'),
('Warsaw','',      'Poland','PL'),
('Athens','',      'Greece','GR'),
('Santorini','',   'Greece','GR'),
('Mykonos','',     'Greece','GR'),
('Crete','',       'Greece','GR'),
('Istanbul','',    'Turkey','TR'),
('Antalya','',     'Turkey','TR'),
('Cappadocia','',  'Turkey','TR'),
('Dublin','',      'Ireland','IE'),
('Copenhagen','',  'Denmark','DK'),
('Stockholm','',   'Sweden','SE'),
('Oslo','',        'Norway','NO'),
('Helsinki','',    'Finland','FI'),
('Lisbon','',      'Portugal','PT'),
('Porto','',       'Portugal','PT'),
('Brussels','',    'Belgium','BE'),
('Reykjavik','',   'Iceland','IS'),
('Dubrovnik','',   'Croatia','HR'),
('Split','',       'Croatia','HR'),

-- ── AMERICAS ────────────────────────────────────────────────
('New York','',     'United States','US'),
('Los Angeles','',  'United States','US'),
('Chicago','',      'United States','US'),
('Miami','',        'United States','US'),
('Las Vegas','',    'United States','US'),
('San Francisco','','United States','US'),
('Orlando','',      'United States','US'),
('Honolulu','',     'United States','US'),
('Washington DC','','United States','US'),
('Toronto','',      'Canada','CA'),
('Vancouver','',    'Canada','CA'),
('Montreal','',     'Canada','CA'),
('São Paulo','',    'Brazil','BR'),
('Rio de Janeiro','','Brazil','BR'),
('Mexico City','',  'Mexico','MX'),
('Cancún','',       'Mexico','MX'),
('Buenos Aires','', 'Argentina','AR'),
('Lima','',         'Peru','PE'),

-- ── OCEANIA ─────────────────────────────────────────────────
('Sydney','',       'Australia','AU'),
('Melbourne','',    'Australia','AU'),
('Brisbane','',     'Australia','AU'),
('Perth','',        'Australia','AU'),
('Gold Coast','',   'Australia','AU'),
('Cairns','',       'Australia','AU'),
('Auckland','',     'New Zealand','NZ'),
('Queenstown','',   'New Zealand','NZ'),
('Christchurch','', 'New Zealand','NZ'),

-- ── AFRICA ──────────────────────────────────────────────────
('Johannesburg','', 'South Africa','ZA'),
('Cape Town','',    'South Africa','ZA'),
('Durban','',       'South Africa','ZA'),
('Nairobi','',      'Kenya','KE'),
('Mombasa','',      'Kenya','KE'),
('Addis Ababa','',  'Ethiopia','ET'),
('Cairo','',        'Egypt','EG'),
('Luxor','',        'Egypt','EG'),
('Hurghada','',     'Egypt','EG'),
('Sharm el-Sheikh','','Egypt','EG'),
('Marrakesh','',    'Morocco','MA'),
('Casablanca','',   'Morocco','MA'),
('Mauritius','',    'Mauritius','MU'),
('Seychelles','',   'Seychelles','SC'),
('Zanzibar','',     'Tanzania','TZ')

ON CONFLICT (name, country_code) DO NOTHING;

-- Index for fast autocomplete search
CREATE INDEX IF NOT EXISTS idx_travel_cities_name ON travel_cities USING gin(to_tsvector('simple', name));
CREATE INDEX IF NOT EXISTS idx_travel_cities_country ON travel_cities (country_code);
